name: Docker - Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Github Packages Deployment
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: extract_version
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --tag ghcr.io/metinkale38/mosque-signage:${VERSION}

      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username metinkale38 --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          docker push ghcr.io/metinkale38/mosque-signage:${VERSION}